version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - NODE_ENV=""
      - NEXT_TELEMETRY_DISABLED=""
      - DATABASE_URL=""
      - NEXTAUTH_URL=""
      - NEXTAUTH_SECRET=""
      - GITHUB_CLIENT_ID=""
      - GITHUB_CLIENT_SECRET=""
      - NEXT_PUBLIC_NEXTAUTH_URL=""
      - NEXT_PUBLIC_SUPABASE_URL=""
      - NEXT_PUBLIC_SUPABASE_PUBLIC_ANON_KEY=""
      - NEXT_PUBLIC_SUPABASE_IMAGE_URL=""
      - NEXT_PUBLIC_HCAPTCHA_SITE_KEY=""
