name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
        env:
          NEXT_PUBLIC_NEXTAUTH_URL: http://localhost:3000
          NEXT_PUBLIC_SUPABASE_URL: zjbjwmzfbmoykisvhhie.supabase.co
          NEXT_PUBLIC_SUPABASE_PUBLIC_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYmp3bXpmYm1veWtpc3ZoaGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzQ0NjQ5OTQsImV4cCI6MTk5MDA0MDk5NH0.LSlghtXGM1Q5e9vEfw2KhyQB9bneFzMMWbVQvkIn6FU
          NEXT_PUBLIC_SUPABASE_IMAGE_URL: https://zjbjwmzfbmoykisvhhie.supabase.co/storage/v1/object/public/surgeapp/
          NEXT_PUBLIC_HCAPTCHA_SITE_KEY: 09b0a265-7e77-438c-91a9-3ae7123a7b8b
          DATABASE_URL: postgresql://postgres:surgeapp1234!@db.zjbjwmzfbmoykisvhhie.supabase.co:5432/postgres
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: VxXp3pH3pCgKfBerXEGAQbplmdSo1LuxCbb40gyXM0w
          GITHUB_CLIENT_ID: 12f25048adbe72b6e419
          GITHUB_CLIENT_SECRET: 6463d8cf05328f08bed16737336f84c06ac40745